from . import (
    test_cargo_info_mixin,
    test_sea_booking,
    test_sea_hbl,
    test_sea_quotation,
    test_analytic_sync,
    test_commercial_group,
    test_minimal_required_fields,
    test_currency_variant_view,
    test_generic_duplicate_commercial_group,
    test_ff73_migration_regression,
    test_ff75_hierarchy_followup,
    test_air_awb_master,
    test_ff79_job_type_account_mapping,
    test_ff80_salesperson,
)
