{
    "name": "Freight Forwarding",
    "version": "18.0.1.8",
    "summary": "Custom Module for Freight Forwarding Management (Clavis Group)",
    "description": """
        Modul custom untuk operasional Freight Forwarding.
    """,
    "category": "Logistics",
    "author": "IT Dev Clavis",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "account",
        "contacts",
        "base_address_extended",
        "hr",
        "hr_expense",
        "purchase",
        "sale_management",
        "stock",
    ],
    "data": [
        # Security
        "security/ir.model.access.csv",
        "security/air/ir.model.access.csv",
        "security/master_data/ir.model.access.csv",
        "security/master_data/acct/ir.model.access.csv",
        "security/master_data/sea/ir.model.access.csv",
        "security/master_data/air/ir.model.access.csv",
        "security/sea/ir.model.access.csv",
        "security/sea/sales/ir.model.access.csv",
        "security/sea/master_data/ir.model.access.csv",
        # Data
        "data/air/air_booking_sequence.xml",
        "data/air/air_mawb_sequence.xml",
        "data/air/air_hawb_sequence.xml",
        "data/sea/sea_booking_sequence.xml",
        "data/sea/sea_hbl_sequence.xml",
        "data/master_data/uom_data.xml",
        "data/quotation/sale_order_sequence.xml",
        # Action
        "views/air/master_data/partner.xml",
        "views/sea/partner.xml",
        "views/transport/partner.xml",
        "views/common/purchase_order.xml",
        "views/common/partner_address.xml",
        "views/common/partner_category.xml",
        "views/common/sale_order_list.xml",
        # Report
        "report/sea/quotation/quotation_report_template.xml",
        "report/sea/quotation/quotation_report.xml",
        "report/sea/hbl/hbl_terms_template.xml",
        "report/sea/hbl/hbl_report_template.xml",
        "report/sea/hbl/hbl_report.xml",
        "report/sea/hbl/cover_jobsheet_report_template.xml",
        "report/sea/hbl/cover_jobsheet_report.xml",
        "report/sea/hbl/shipping_instruction_report_template.xml",
        "report/sea/hbl/shipping_instruction_report.xml",
        "report/sea/hbl/report_noa_sysfreight_template.xml",
        "report/sea/hbl/report_noa_sysfreight.xml",
        "report/sea/hbl/cargo_manifest_report_template.xml",
        "report/sea/hbl/cargo_manifest_report.xml",
        # Sea Quotation
        "views/sea/sales/quotation.xml",
        "views/sea/sales/migration_wizard.xml",

        "views/sea/sales/rate_enquiry_actions.xml",
        # Air Quotation
        "views/air/sales/quotation.xml",
        "views/sea/booking/booking.xml",
        "views/sea/booking/extra_info_views.xml",
        "views/sea/booking/cargo_info.xml",
        "views/sea/booking/booking_convert_wizard.xml",
        "views/sea/hbl/cargo_info.xml",
        "views/sea/hbl/custom_permit.xml",
        "views/sea/hbl/tax_refund_doc_views.xml",
        "views/sea/hbl/document_list_views.xml",
        "views/sea/hbl/hbl.xml",
        "views/sea/import/purchasing.xml",
        # Air
        "views/air/booking/booking.xml",
        "views/air/hawb/document_list_views.xml",
        "views/air/hawb/hawb.xml",
        # Master Data
        "views/air/master_data/insurance.xml",
        "views/air/master_data/pickup.xml",
        "views/air/master_data/cargo_type.xml",
        "views/air/master_data/contact.xml",
        "views/air/master_data/tag.xml",
        "views/air/master_data/incoterms.xml",
        "views/master_data/job_type.xml",
        "views/master_data/declaration.xml",
        "views/master_data/cargo_class.xml",
        "views/master_data/dg_class_code.xml",
        "views/master_data/quotation_type.xml",
        "views/master_data/delivery_type.xml",
        "views/master_data/commodity.xml",
        "views/master_data/permit.xml",
        "views/master_data/shipment_type.xml",
        # Master Data - Account
        "views/master_data/acct/area.xml",
        "views/master_data/acct/charge_code.xml",
        "views/master_data/acct/division.xml",
        "views/master_data/acct/payment_term.xml",
        "views/master_data/acct/vat_code.xml",
        # Master Data - Sea
        "views/master_data/sea/port.xml",
        "views/master_data/sea/vessel.xml",
        "views/master_data/sea/shipping_line.xml",
        "views/master_data/sea/container_type.xml",
        # Master Data - Air
        "views/master_data/air/airport.xml",
        "views/master_data/air/airline.xml",
        "views/sea/master_data/carrier.xml",
        "views/sea/master_data/location.xml",
        "views/sea/master_data/footer_remark.xml",
        "views/sea/master_data/instruction.xml",
        # Menu
        "views/menu.xml",
        "views/menus/air.xml",
        "views/menus/sea.xml",
        "views/menus/master.xml",
        # Harus dimuat SETELAH views/menus/master.xml -- menuitem di file ini
        # mereferensikan parent="menu_sub_parent_air_master_data" yang
        # didefinisikan di sana (bug urutan lama, baru kena pada fresh install).
        "views/air/master_data/handling_information.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
    "tests": [
        "tests/test_cargo_info_mixin.py",
        "tests/test_sea_booking.py",
        "tests/test_sea_hbl.py",
        "tests/test_sea_quotation.py",
        "tests/test_analytic_sync.py",
        "tests/test_commercial_group.py",
        "tests/test_minimal_required_fields.py",
        "tests/test_currency_variant_view.py",
    ],
}