[options]
addons_path = /mnt/extra-addons/custom1,/mnt/extra-addons/custom2
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$7r1XqpVSKoWQUopxTun9Hw$pFuGeGvxlNOJ9Tz/g.FosgTKM8pkEYWqSWgourx5LPM5WYqZTj.LZSvRRZGbRWKKX7insSHcfc8TZoKclp20uA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

